sudo: required
services:
  - docker

before_install:
  - docker build -t studentaleksandr/docker-react-app -f Dockerfile.dev .

script:
  - docker run studentaleksandr/docker-react-app yarn test --coverage